// code/angular-app/src/app/add-note-wrapper/add-note-wrapper.component.ts
import { Component } from '@angular/core';
import { AppService } from '../app.service';

@Component({
  selector: 'add-note-wrapper',
  template: `
    <div class="add-note-wrapper">
      <div class="note-title-wrapper">
        <input 
          class="note-title-input" 
          placeholder="Note title..."
          [(ngModel)]="title"
          />
      </div>
      <div 
        class="add-note-button"
        (click)="addNote()"
        >
        +
      </div>
    </div>
  `,
  styleUrls: ['./add-note-wrapper.component.css']
})
export class AddNoteWrapperComponent {
  title: string = '';

  constructor(private appService: AppService) { }

  addNote() {
    this.appService.addNote(this.title);
    this.title = '';
  }
}

<div class="add-note-wrapper">
  <div class="note-title-wrapper">
    <input 
      class="note-title-input" 
      placeholder="Note title..."
      />
  </div>
  <div 
    class="add-note-button">
    +
  </div>
</div>

// code/react-app/src/components/add-note-wrapper/AddNoteWrapper.tsx
import React, { useCallback, useState } from 'react';

interface IProps {
  addNote: (title: string) => void;
} 

export function AddNoteWrapper(props: IProps) {
  const [title, setTitle] = useState<string>('');

  const onAddCallback = useCallback(
    () => {
      if (title) {
        props.addNote(title);
        setTitle('');
      }
    },
    [title],
  );

  return (
    <div className="add-note-wrapper">
      <div className="note-title-wrapper">
        <input 
          className="note-title-input" 
          placeholder="Note title..."
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          />
      </div>
      <div 
        className="add-note-button" 
        onClick={onAddCallback}>
        +
      </div>
    </div>
  );
}
