// code/vue-app/src/components/ScrollableNotesList.vue
<template>
  <div className="scrollable-notes-list">
    <div v-for="(note, index) in notes" :key="note.id">
      <NoteItem v-bind:note="note" v-bind:isActive="index === currentIndex" />
    </div>
  </div>
</template>

<script lang="ts">
import NoteItem from './NoteItem.vue';
import { Options, Vue } from "vue-class-component";
import { GlobalState } from '@/state/app.state';

@Options({
  data: () => GlobalState,
  components: {
    NoteItem,
  },
})
export default class ScrollableNotesList extends Vue {}
</script>

<style>
.scrollable-notes-list {
  overflow-y: auto;
  height: calc(100vh + -50px);
}
</style>

// code/react-app/src/components/scrollable-notes-list/ScrollableNotesList.tsx
import React from 'react';
import { INoteModel } from '../../models/note.model';
import { NoteItem } from '../note-item/NoteItem';

interface IProps {
  notes: INoteModel[];
  setCurrentNote: (id: string) => void;
  currentNoteIndex?: number;
}

export function ScrollableNotesList(props: IProps) {
  return (
    <div className="scrollable-notes-list">
      {props.notes.map((note, index) => (
        <NoteItem 
          note={note} 
          setCurrentNote={props.setCurrentNote}
          isActive={index === props.currentNoteIndex}
          />
      ))}
    </div>
  );
}
